# Site settings
#remote_theme:: jekyll-theme-clean-blog
title: #
description: Bесёлый отдых и незабываемые впечатления! Уникальная возможность, в первую очередь для детей, поговорить по-русски на французской земле!
cover: assets/images/cover.png
logo: assets/images/logo.png
favicon: assets/favicon/favicon-32x32.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://a-club-france.github.io/" # the base hostname & protocol for your site
timezone: 'Europe/Paris'
email: kirill.vankov@gmail.com # todo : artclub.grenoble@gmail.com
author: А-Клуб
formspreeApi: mnqgdkkj

# Social Profiles
#twitter_username:
#github_username:
#facebook_username:
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
