# Site settings
title: А-Клуб
description: Bесёлый отдых и незабываемые впечатления! Уникальная возможность, в первую очередь для детей, поговорить по-русски на французской земле!
cover: assets/images/cover.png
logo: assets/images/logo.png
favicon: assets/favicon/favicon-32x32.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://a-club-france.github.io/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown
# see https://kramdown.gettalong.org/quickref.html

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: a-club-france #github username
repo: a-club-france #github repository
branch: master #branch
relative_source: ../a-club-france/ #source directory
destination: ../a-club-france-pages/ #destination directory
production_url:  https://a-club-france.github.io/
source_url:  https://github.com/a-club-france/a-club-france.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
